# docker compose up -d
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:9000